src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PhotoRepository::class)]
class Photo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $photo_link = null;

    #[ORM\ManyToMany(targetEntity: gite::class, inversedBy: 'photos')]
    private Collection $gite_photo;

    public function __construct()
    {
        $this->gite_photo = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhotoLink(): ?string
    {
        return $this->photo_link;
    }

    public function setPhotoLink(string $photo_link): self
    {
        $this->photo_link = $photo_link;

        return $this;
    }

    /**
     * @return Collection<int, gite>
     */
    public function getGitePhoto(): Collection
    {
        return $this->gite_photo;
    }

    public function addGitePhoto(gite $gitePhoto): self
    {
        if (!$this->gite_photo->contains($gitePhoto)) {
            $this->gite_photo->add($gitePhoto);
        }

        return $this;
    }

    public function removeGitePhoto(gite $gitePhoto): self
    {
        $this->gite_photo->removeElement($gitePhoto);

        return $this;
    }
}

src/Form/PhotoType.php
<?php

namespace App\Form;

use App\Entity\Photo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PhotoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('photo_link')
            ->add('gite_photo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Photo::class,
        ]);
    }
}

src/Controller/PhotoController.php
<?php

namespace App\Controller;

use App\Entity\Photo;
use App\Form\PhotoType;
use App\Repository\PhotoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/photo')]
class PhotoController extends AbstractController
{
    #[Route('/', name: 'app_photo_index', methods: ['GET'])]
    public function index(PhotoRepository $photoRepository): Response
    {
        return $this->render('photo/index.html.twig', [
            'photos' => $photoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_photo_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PhotoRepository $photoRepository): Response
    {
        $photo = new Photo();
        $form = $this->createForm(PhotoType::class, $photo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $photoRepository->save($photo, true);

            return $this->redirectToRoute('app_photo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('photo/new.html.twig', [
            'photo' => $photo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_photo_show', methods: ['GET'])]
    public function show(Photo $photo): Response
    {
        return $this->render('photo/show.html.twig', [
            'photo' => $photo,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_photo_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Photo $photo, PhotoRepository $photoRepository): Response
    {
        $form = $this->createForm(PhotoType::class, $photo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $photoRepository->save($photo, true);

            return $this->redirectToRoute('app_photo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('photo/edit.html.twig', [
            'photo' => $photo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_photo_delete', methods: ['POST'])]
    public function delete(Request $request, Photo $photo, PhotoRepository $photoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$photo->getId(), $request->request->get('_token'))) {
            $photoRepository->remove($photo, true);
        }

        return $this->redirectToRoute('app_photo_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/photo/_delete_form.html.twig
<form method="post" action="{{ path('app_photo_delete', {'id': photo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ photo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/photo/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/photo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Photo{% endblock %}

{% block body %}
    <h1>Edit Photo</h1>

    {{ include('photo/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_photo_index') }}">back to list</a>

    {{ include('photo/_delete_form.html.twig') }}
{% endblock %}

templates/photo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Photo index{% endblock %}

{% block body %}
    <h1>Photo index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Photo_link</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for photo in photos %}
            <tr>
                <td>{{ photo.id }}</td>
                <td>{{ photo.photoLink }}</td>
                <td>
                    <a href="{{ path('app_photo_show', {'id': photo.id}) }}">show</a>
                    <a href="{{ path('app_photo_edit', {'id': photo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_photo_new') }}">Create new</a>
{% endblock %}

templates/photo/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Photo{% endblock %}

{% block body %}
    <h1>Create new Photo</h1>

    {{ include('photo/_form.html.twig') }}

    <a href="{{ path('app_photo_index') }}">back to list</a>
{% endblock %}

templates/photo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Photo{% endblock %}

{% block body %}
    <h1>Photo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ photo.id }}</td>
            </tr>
            <tr>
                <th>Photo_link</th>
                <td>{{ photo.photoLink }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_photo_index') }}">back to list</a>

    <a href="{{ path('app_photo_edit', {'id': photo.id}) }}">edit</a>

    {{ include('photo/_delete_form.html.twig') }}
{% endblock %}