src/Entity/Gite.php
<?php

namespace App\Entity;

use App\Repository\GiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GiteRepository::class)]
class Gite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToMany(targetEntity: EquipmentInt::class, inversedBy: 'gites')]
    private Collection $GiteEquipmentInt;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 255)]
    private ?string $departement = null;

    #[ORM\Column(length: 255)]
    private ?string $region = null;

    #[ORM\Column]
    private ?float $surface = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\Column]
    private ?int $beds = null;

    #[ORM\Column]
    private ?bool $animal_allowed = null;

    #[ORM\Column(nullable: true)]
    private ?float $animal_cost = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $disponibilities = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $green_price = null;

    #[ORM\Column(nullable: true)]
    private ?int $red_price = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $start_red = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $end_red = null;

    #[ORM\ManyToMany(targetEntity: EquipmentExt::class, mappedBy: 'gite_equipment_ext')]
    private Collection $equipmentExts;

    #[ORM\ManyToMany(targetEntity: Photo::class, mappedBy: 'gite_photo')]
    private Collection $photos;

    #[ORM\OneToMany(mappedBy: 'id_gite', targetEntity: GiteService::class)]
    private Collection $giteServices;

    public function __construct()
    {
        $this->GiteEquipmentInt = new ArrayCollection();
        $this->equipmentExts = new ArrayCollection();
        $this->photos = new ArrayCollection();
        $this->giteServices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, EquipmentInt>
     */
    public function getGiteEquipmentInt(): Collection
    {
        return $this->GiteEquipmentInt;
    }

    public function addGiteEquipmentInt(EquipmentInt $giteEquipmentInt): self
    {
        if (!$this->GiteEquipmentInt->contains($giteEquipmentInt)) {
            $this->GiteEquipmentInt->add($giteEquipmentInt);
        }

        return $this;
    }

    public function removeGiteEquipmentInt(EquipmentInt $giteEquipmentInt): self
    {
        $this->GiteEquipmentInt->removeElement($giteEquipmentInt);

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBeds(): ?int
    {
        return $this->beds;
    }

    public function setBeds(int $beds): self
    {
        $this->beds = $beds;

        return $this;
    }

    public function isAnimalAllowed(): ?bool
    {
        return $this->animal_allowed;
    }

    public function setAnimalAllowed(bool $animal_allowed): self
    {
        $this->animal_allowed = $animal_allowed;

        return $this;
    }

    public function getAnimalCost(): ?float
    {
        return $this->animal_cost;
    }

    public function setAnimalCost(?float $animal_cost): self
    {
        $this->animal_cost = $animal_cost;

        return $this;
    }

    public function getDisponibilities(): ?string
    {
        return $this->disponibilities;
    }

    public function setDisponibilities(string $disponibilities): self
    {
        $this->disponibilities = $disponibilities;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getGreenPrice(): ?int
    {
        return $this->green_price;
    }

    public function setGreenPrice(int $green_price): self
    {
        $this->green_price = $green_price;

        return $this;
    }

    public function getRedPrice(): ?int
    {
        return $this->red_price;
    }

    public function setRedPrice(?int $red_price): self
    {
        $this->red_price = $red_price;

        return $this;
    }

    public function getStartRed(): ?\DateTimeInterface
    {
        return $this->start_red;
    }

    public function setStartRed(?\DateTimeInterface $start_red): self
    {
        $this->start_red = $start_red;

        return $this;
    }

    public function getEndRed(): ?\DateTimeInterface
    {
        return $this->end_red;
    }

    public function setEndRed(?\DateTimeInterface $end_red): self
    {
        $this->end_red = $end_red;

        return $this;
    }

    /**
     * @return Collection<int, EquipmentExt>
     */
    public function getEquipmentExts(): Collection
    {
        return $this->equipmentExts;
    }

    public function addEquipmentExt(EquipmentExt $equipmentExt): self
    {
        if (!$this->equipmentExts->contains($equipmentExt)) {
            $this->equipmentExts->add($equipmentExt);
            $equipmentExt->addGiteEquipmentExt($this);
        }

        return $this;
    }

    public function removeEquipmentExt(EquipmentExt $equipmentExt): self
    {
        if ($this->equipmentExts->removeElement($equipmentExt)) {
            $equipmentExt->removeGiteEquipmentExt($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->addGitePhoto($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->removeElement($photo)) {
            $photo->removeGitePhoto($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, GiteService>
     */
    public function getGiteServices(): Collection
    {
        return $this->giteServices;
    }

    public function addGiteService(GiteService $giteService): self
    {
        if (!$this->giteServices->contains($giteService)) {
            $this->giteServices->add($giteService);
            $giteService->setIdGite($this);
        }

        return $this;
    }

    public function removeGiteService(GiteService $giteService): self
    {
        if ($this->giteServices->removeElement($giteService)) {
            // set the owning side to null (unless already changed)
            if ($giteService->getIdGite() === $this) {
                $giteService->setIdGite(null);
            }
        }

        return $this;
    }
}

src/Form/GiteType.php
<?php

namespace App\Form;

use App\Entity\Gite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('adress')
            ->add('city')
            ->add('zipcode')
            ->add('departement')
            ->add('region')
            ->add('surface')
            ->add('rooms')
            ->add('beds')
            ->add('animal_allowed')
            ->add('animal_cost')
            ->add('disponibilities')
            ->add('description')
            ->add('green_price')
            ->add('red_price')
            ->add('start_red')
            ->add('end_red')
            ->add('GiteEquipmentInt')
            ->add('equipmentExts')
            ->add('photos')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Gite::class,
        ]);
    }
}

src/Controller/GiteController.php
<?php

namespace App\Controller;

use App\Entity\Gite;
use App\Form\GiteType;
use App\Repository\GiteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/gite')]
class GiteController extends AbstractController
{
    #[Route('/', name: 'app_gite_index', methods: ['GET'])]
    public function index(GiteRepository $giteRepository): Response
    {
        return $this->render('gite/index.html.twig', [
            'gites' => $giteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_gite_new', methods: ['GET', 'POST'])]
    public function new(Request $request, GiteRepository $giteRepository): Response
    {
        $gite = new Gite();
        $form = $this->createForm(GiteType::class, $gite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $giteRepository->save($gite, true);

            return $this->redirectToRoute('app_gite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('gite/new.html.twig', [
            'gite' => $gite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_gite_show', methods: ['GET'])]
    public function show(Gite $gite): Response
    {
        return $this->render('gite/show.html.twig', [
            'gite' => $gite,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_gite_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Gite $gite, GiteRepository $giteRepository): Response
    {
        $form = $this->createForm(GiteType::class, $gite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $giteRepository->save($gite, true);

            return $this->redirectToRoute('app_gite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('gite/edit.html.twig', [
            'gite' => $gite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_gite_delete', methods: ['POST'])]
    public function delete(Request $request, Gite $gite, GiteRepository $giteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$gite->getId(), $request->request->get('_token'))) {
            $giteRepository->remove($gite, true);
        }

        return $this->redirectToRoute('app_gite_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/gite/_delete_form.html.twig
<form method="post" action="{{ path('app_gite_delete', {'id': gite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ gite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/gite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/gite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Gite{% endblock %}

{% block body %}
    <h1>Edit Gite</h1>

    {{ include('gite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_gite_index') }}">back to list</a>

    {{ include('gite/_delete_form.html.twig') }}
{% endblock %}

templates/gite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gite index{% endblock %}

{% block body %}
    <h1>Gite index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Adress</th>
                <th>City</th>
                <th>Zipcode</th>
                <th>Departement</th>
                <th>Region</th>
                <th>Surface</th>
                <th>Rooms</th>
                <th>Beds</th>
                <th>Animal_allowed</th>
                <th>Animal_cost</th>
                <th>Disponibilities</th>
                <th>Description</th>
                <th>Green_price</th>
                <th>Red_price</th>
                <th>Start_red</th>
                <th>End_red</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for gite in gites %}
            <tr>
                <td>{{ gite.id }}</td>
                <td>{{ gite.name }}</td>
                <td>{{ gite.adress }}</td>
                <td>{{ gite.city }}</td>
                <td>{{ gite.zipcode }}</td>
                <td>{{ gite.departement }}</td>
                <td>{{ gite.region }}</td>
                <td>{{ gite.surface }}</td>
                <td>{{ gite.rooms }}</td>
                <td>{{ gite.beds }}</td>
                <td>{{ gite.animalAllowed ? 'Yes' : 'No' }}</td>
                <td>{{ gite.animalCost }}</td>
                <td>{{ gite.disponibilities }}</td>
                <td>{{ gite.description }}</td>
                <td>{{ gite.greenPrice }}</td>
                <td>{{ gite.redPrice }}</td>
                <td>{{ gite.startRed ? gite.startRed|date('Y-m-d') : '' }}</td>
                <td>{{ gite.endRed ? gite.endRed|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_gite_show', {'id': gite.id}) }}">show</a>
                    <a href="{{ path('app_gite_edit', {'id': gite.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="19">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_gite_new') }}">Create new</a>
{% endblock %}

templates/gite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Gite{% endblock %}

{% block body %}
    <h1>Create new Gite</h1>

    {{ include('gite/_form.html.twig') }}

    <a href="{{ path('app_gite_index') }}">back to list</a>
{% endblock %}

templates/gite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gite{% endblock %}

{% block body %}
    <h1>Gite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ gite.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ gite.name }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ gite.adress }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ gite.city }}</td>
            </tr>
            <tr>
                <th>Zipcode</th>
                <td>{{ gite.zipcode }}</td>
            </tr>
            <tr>
                <th>Departement</th>
                <td>{{ gite.departement }}</td>
            </tr>
            <tr>
                <th>Region</th>
                <td>{{ gite.region }}</td>
            </tr>
            <tr>
                <th>Surface</th>
                <td>{{ gite.surface }}</td>
            </tr>
            <tr>
                <th>Rooms</th>
                <td>{{ gite.rooms }}</td>
            </tr>
            <tr>
                <th>Beds</th>
                <td>{{ gite.beds }}</td>
            </tr>
            <tr>
                <th>Animal_allowed</th>
                <td>{{ gite.animalAllowed ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Animal_cost</th>
                <td>{{ gite.animalCost }}</td>
            </tr>
            <tr>
                <th>Disponibilities</th>
                <td>{{ gite.disponibilities }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ gite.description }}</td>
            </tr>
            <tr>
                <th>Green_price</th>
                <td>{{ gite.greenPrice }}</td>
            </tr>
            <tr>
                <th>Red_price</th>
                <td>{{ gite.redPrice }}</td>
            </tr>
            <tr>
                <th>Start_red</th>
                <td>{{ gite.startRed ? gite.startRed|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_red</th>
                <td>{{ gite.endRed ? gite.endRed|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_gite_index') }}">back to list</a>

    <a href="{{ path('app_gite_edit', {'id': gite.id}) }}">edit</a>

    {{ include('gite/_delete_form.html.twig') }}
{% endblock %}